# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a49c113292d00c12bfc40bbb4f8a3d1b2f4f4adb0b22385f19c51c8f1352658f7e890d010232c06adc6da427f9823f2b5d67bd4f9fdeab825784dda3dc2e9969

test:
  secret_key_base: ac9a6e845596dbf63a00d62d6866d8f4e9ffcd5ebafee6ab59ab45102aaa0b51dcab865144aa72ccd57729db62f261d8ac0cad9bef17cb7358917aa82271909c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
